"""Add actual_net_pay to PayPeriodStatus

Revision ID: 001ce55c3c1a
Revises: 
Create Date: 2025-06-12 13:53:08.378962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001ce55c3c1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agency_shift')
    with op.batch_alter_table('pay_period_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_net_pay', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pay_period_status', schema=None) as batch_op:
        batch_op.drop_column('actual_net_pay')

    op.create_table('agency_shift',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shift_date', sa.DATE(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.Column('hourly_rate', sa.FLOAT(), nullable=False),
    sa.Column('break_minutes', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
